### ISSUE TITLE
UserImage.js

### ISSUE THREAD

**Issue by rymatech** [fac18/roshjud-react#10]
`        <fieldset>
          <legend>User</legend>
          <label for="gitHandle"></label>
          <input
            placeholder="Enter user name"
            type="text"
            id="gitHandle"
            name="gitHandle"
            value={gitHandle}
            onChange={event => setGitHandle(event.target.value)}
          ></input>
          <input type="submit" value="submit"></input>
        </fieldset>`

 nothing inside the input tag, therefore change to the below (.i.e. NOT <input></input> instead <input/>)

`          <label for="gitHandle"/>
          <input
  placeholder="Enter user name"
  type="text"
  id="gitHandle"
  name="gitHandle"
  value={gitHandle}
  onChange={event => setGitHandle(event.target.value)}
  />
          <input type="submit" value="submit"/>`

**Comment by oliverjam** [comment]
Yeah empty tags should self-close. I.e. `<input></input>`->`<input />`
