### ISSUE TITLE
ScoredCard.js

### ISSUE THREAD

**Issue by rymatech** [fac18/roshjud-react#9]
line 30:         Your mission is:{mission[Math.floor(Math.random() * (3 - 1 + 1) + 0)]}

I believe could be shortened to:

 Your mission is:{mission[Math.floor(Math.random() * (3 - 1 + 1))]}

**Comment by rosalie-baxter** [comment]
Second this! The current line doesn't seem to be working on my computer so was going to suggest a change also :)
